### ISSUE TITLE
调用删除菜单报错

### ISSUE THREAD

**Issue by lihy0133** [silenceper/wechat#157]
`wc := wechat.NewWechat(config)
	mu := wc.GetMenu()

	err:=mu.DeleteMenu()`

以下是日志
` http: panic serving 127.0.0.1:41072: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc00007b400)
	/root/go/src/net/http/server.go:1767 +0x139
panic(0x7ef4c0, 0xb8a680)
	/root/go/src/runtime/panic.go:679 +0x1b2
github.com/silenceper/wechat/context.(*Context).GetAccessToken(0xc00008ed10, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/pkg/mod/github.com/silenceper/wechat@v2.0.0+incompatible/context/access_token.go:47 +0x13e
github.com/silenceper/wechat/menu.(*Menu).DeleteMenu(0xc0000489a0, 0xc00019a480, 0x415213)
	/root/gopath/pkg/mod/github.com/silenceper/wechat@v2.0.0+incompatible/menu/menu.go:167 +0x32
`

**Comment by silenceper** [comment]
有设置cache来保存access_token吗？
